brew "asdf"
brew "ctags"
brew "direnv"
brew "fish"
brew "git"
brew "heroku"
brew "jump"
brew "openssl"
brew "postgresql"
brew "redis"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "wget"
brew "youtube-dl"

# Cask
cask_args appdir: "/Applications"
tap "caskroom/cask"
# cask alfred
cask "appcleaner"
cask "cloudapp"
cask "dash"
# cask "divvy"
cask "dropbox"
cask "docker"
cask "flux"
# cask "google-chrome"
# cask "iterm2"
cask "imageoptim"
cask "skype"
cask "caskroom/versions/slack-beta"
# cask "spotify"
cask "transmission"
# cask "vlc"
