#!/usr/bin/env bash

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

if [ ! -f .rubocop.yml ]; then
  # Rubocop not setup for this repo
  exit 0
fi

if ! command -v bundle exec rubocop > /dev/null; then
  # Rubocop config file present but Rubocop not installed
  printf "${CLEAR_LINE}💀${RED}   Install Rubocop and be sure it is available on your PATH${NO_COLOR}\n"
  printf "ℹ️   Try 'gem install rubocop'\n"
  exit -1
fi

printf "🚔    Linting with Rubocop..."

suspects="$(comm -12 <(git diff --cached --name-only --diff-filter=AMC | sort) <(bundle exec rubocop --list-target-files 2> /dev/null | sort) | tr '\n' ' ')"

if [ -n "$suspects" ]; then
  printf "${CLEAR_LINE}🚔   Linting files: ${suspects}\n"

  # Run rubocop on the staged files
  if ! bundle exec rubocop --format simple ${suspects} #> /dev/null
  then
    printf "${CLEAR_LINE}${RED}💀   Rubocop found some issues. Fix, stage, and commit again${NO_COLOR}\n"
    printf "ℹ️   Try 'rubocop --format simple --auto-correct && git add -p'\n"
    exit -1
  fi
fi

printf "${CLEAR_LINE}🎉${GREEN}   Rubocop is appeased.${NO_COLOR}\n"
exit 0
